# Linear algebra

This is a lab that helps you learn linear algebra (and the related numpy commands.)  Consult Greene "Econometric Analysis" Appendix A when solving these problems.


Import appropriate packages

In [62]:
import numpy as np
import matplotlib.pyplot as plt
import math as math
%matplotlib inline

## 1 Matrix multiplication
* create the following matrices:
a = [ 1 2 3 4], b = [5 6 7 8 ]'
(note: b includes the transpose sign)
* compute the following matrix products $a \cdot b$ and $a' \cdot b'$

In [63]:
a = np.matrix("1 2 3 4")
print(a)
b = np.matrix('5 6 7 8')
print(b)
bt = b.T
print(bt)
at = a.T
#print(at @ bt)
print(a * bt)
print(b*at)

[[1 2 3 4]]
[[5 6 7 8]]
[[5]
 [6]
 [7]
 [8]]
[[70]]
[[70]]


## 2 Linear (in)dependence
Consider three vectors:
a = [1 2 3 4],
b = [5 6 7 8] and
c = [9 10 11 12]

* are these vectors linearly independent?  Calculate the rank, a related determinant, and show how they are related/unrelated

In [64]:
c = np.matrix('9 10 11 12')
A = np.matrix('1 2 3 4; 5 6 7 8; 9 10 11 12')
print(A)
print(np.linalg.matrix_rank(A))
# the determinant of this matrix is zero because it is not full ranked (rank = 2), which means it is dependendent

# showing determinent == 0
# fist make a square matrix by multiplying by transpose
At = np.transpose(A)
print(np.linalg.det(A@At)) 


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
2
0.0


## 3 Find the inverses of the following matrices:


A = [ <br/>
    1 2 3 4 <br/>
5 6 7 8 <br/>
-1 10 11 12 <br/>
13 14 15 17 ],

B = [ <br/>
    1 0 0 <br/>
     0 4 0 <br/>
     0 0 16]

and

C = [ <br/>
    1 2 3 4 <br/>
      5 6 7 8 <br/>
      9 10 11 12 <br/>
      13 14 15 17 ]

* Check the results by left- and right multiplication of the inverse.  Explain.

In [65]:
# construction of matrix
A = np.matrix('1 2 3 4; 5 6 7 8; -1 10 11 12; 13 14 15 17')
B = np.matrix('1 0 0; 0 4 0; 0 0 16')
C = np.matrix('1 2 3 4; 5 6 7 8; 9 10 11 12; 13 14 15 17')
print(A)
print(B)
print(C)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [-1 10 11 12]
 [13 14 15 17]]
[[ 1  0  0]
 [ 0  4  0]
 [ 0  0 16]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 17]]


In [66]:
A_in = np.linalg.inv(A)
print('\n','Inverse of Matrix A and left/right multiplication')
print('\n', A_in)
print('\n', A @ A_in)
print('\n', A_in @ A)
print('\n','Inverse of Matrix B and left/right multiplication')
B_in = np.linalg.inv(B)
print('\n', B_in)
print('\n', B @ B_in)
print('\n', B_in @ B)
print('\n', 'Inverse of Matrix C and left/right multiplication')
C_in = np.linalg.inv(C)
print('\n', C_in)
print('\n', C @ C_in)
print('\n', C_in @ C)


 Inverse of Matrix A and left/right multiplication

 [[-1.00000000e-01  2.00000000e-01 -1.00000000e-01  6.83214169e-16]
 [ 4.50000000e-01 -2.65000000e+00  2.00000000e-01  1.00000000e+00]
 [-2.60000000e+00  5.70000000e+00 -1.00000000e-01 -2.00000000e+00]
 [ 2.00000000e+00 -3.00000000e+00 -2.08166817e-16  1.00000000e+00]]

 [[ 1.00000000e+00 -1.77635684e-15  2.85962078e-30  4.44089210e-16]
 [ 3.55271368e-15  1.00000000e+00  5.71924156e-30  2.66453526e-15]
 [ 0.00000000e+00  7.10542736e-15  1.00000000e+00 -1.77635684e-15]
 [ 0.00000000e+00  0.00000000e+00  1.38777878e-17  1.00000000e+00]]

 [[ 1.00000000e+00  2.12650410e-15  2.47665136e-15  2.95490128e-15]
 [ 0.00000000e+00  1.00000000e+00  0.00000000e+00 -3.55271368e-15]
 [ 3.55271368e-15  0.00000000e+00  1.00000000e+00  7.10542736e-15]
 [-1.77635684e-15 -3.55271368e-15 -1.77635684e-15  1.00000000e+00]]

 Inverse of Matrix B and left/right multiplication

 [[1.     0.     0.    ]
 [0.     0.25   0.    ]
 [0.     0.     0.0625]]

 [[1. 0

## 4 Characteristic roots
* Find the roots (eigenvalues) of the matrices A, B, C above.
* Calculate the condition numbers of these matrices in two ways: the default numpy way, and in this way as it is explained in Greene (2003, page 829)
* Explain the results

In [134]:
val, vec = np.linalg.eig(A)
print('\neigenvalue, eigenvector A\n', val)
print('\n',vec)
a_max = val.max()
a_min = val.min()

val, vec = np.linalg.eig(B)
print('\neigenValue, eigenvector B\n', val)
print('\n',vec)
b_max = val.max()
b_min = val.min()

val,vec = np.linalg.eig(C)
print('\neigenValue, eigenvector C\n', val)
print('\n',vec)
c_max = val.max()
c_min = val.min()


eigenvalue, eigenvector A
 [35.83449756  1.34371891 -1.6853005  -0.49291597]

 [[-0.15251646 -0.1275233   0.22153696  0.08211323]
 [-0.35160514 -0.13224317 -0.177807   -0.38931136]
 [-0.50813247  0.81206955  0.73737404  0.80513068]
 [-0.77130664 -0.55388862 -0.61285036 -0.43983936]]

eigenValue, eigenvector B
 [ 1.  4. 16.]

 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

eigenValue, eigenvector C
 [ 3.66727818e+01 -2.00000000e+00 -1.94167590e-15  3.27218155e-01]

 [[-1.49188579e-01 -7.74596669e-01  4.08248290e-01  2.93452674e-01]
 [-3.44038583e-01 -2.58198890e-01 -8.16496581e-01 -2.12087586e-01]
 [-5.38888587e-01  2.58198890e-01  4.08248290e-01 -7.17627846e-01]
 [-7.54307174e-01  5.16397779e-01  6.25005737e-16  5.94907269e-01]]


In [141]:
print('Condition number Matrix A with numpy\n', np.linalg.cond(A))
print('Condition number Matrix B with numpy\n', np.linalg.cond(B))
print('Condition number Matrix C with numpy\n', np.linalg.cond(C))

Condition number Matrix A with numpy
 299.0502040824254
Condition number Matrix B with numpy
 16.0
Condition number Matrix C with numpy
 2.9175891704368506e+17


In [144]:
import operator
def CondNumber(val_max, val_min):
    cond = (val_max/val_min)**0.5
    return cond
    

In [145]:
print('Calculated Cond Number A \n', CondNumber(a_max, a_min))
print('Calculated Cond Number A \n', CondNumber(b_max, b_min))
print('Calculated Cond Number A \n', CondNumber(c_max, c_min))


Calculated Cond Number A 
 nan
Calculated Cond Number A 
 4.0
Calculated Cond Number A 
 nan


C:\Users\maryh\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: RuntimeWarning: invalid value encountered in double_scalars
  This is separate from the ipykernel package so we can avoid doing imports until


There are many ways to compute the conditional number. Numpy must default to a ceratain way (norm?) while the we shown in appendex A uses a different method. Since the way in the text does not allow a negitave value to be a condition (by taking a squareroot) we have NaN values present. Perhpas Numpy uses abs or finds complex-number solutions. 